services:
  compare-viz:
    build:
      context: .
      dockerfile: Dockerfile
    image: compare-viz:latest
    container_name: compare-viz
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    environment:
      - TZ=Asia/Tokyo
    networks:
      - viz-network

networks:
  viz-network:
    driver: bridge